### ISSUE TITLE
Flatpak version of Opera fails to load libwidevinecdm.so

### ISSUE THREAD

**Issue by finesseseth** [flathub/com.opera.Opera#35] opened 2023-06-23 00:53 UTC
I recently decided to give Opera another go after hearing about their new release, so far pretty happy with it - but there is an issue I haven't been able to solve yet with the Flatpak version.

I've tested Opera from community Manjaro repo's, AUR and Snap (after some fiddling) and got them all working.

I don't know if this is related to sandboxing or not. I get these messages when trying to run widevine encoded content:
`[651:405:0623/092718.993705:ERROR:cdm_module.cc(114)] CDM at /home/<user>/.var/app/com.opera.Opera/config/opera/WidevineCdm/4.10.2652.1/_platform_specific/linux_x64/libwidevinecdm.so could not be loaded.
[651:405:0623/092718.993780:ERROR:cdm_module.cc(115)] Error: /home/<user>/.var/app/com.opera.Opera/config/opera/WidevineCdm/4.10.2652.1/_platform_specific/linux_x64/libwidevinecdm.so: cannot open shared object file: Operation not permitted`

All Flatpaks are installed globally.

I've done the following:
* Replaced '/var/lib/flatpak/app/com.opera.Opera/x86_64/stable/active/files/opera/libffmpeg.so' with one that supports h264 etc. Without this change I don't think Opera even attempts to load libwidevinecdm.so.
* Replacing libwidevinecdm.so.
* Checking that all required libraries are in place and readable (checked with ldd while inside the sandbox).
* Manually copying the required libraries and setting up LD_LIBRARY_PATH with '--env' switch.
* Rolling back Flatpak Opera to pre-100 versions going back a few versions to see if any of them work.
* Using Flatseal, trying relevant permissions/settings that other browsers have (Firefox/Chrome with working widevine etc)
* Googled with nothing relevant coming up except for someone who noticed the same thing > https://discourse.flathub.org/t/flatpak-dev-question-app-cannot-load-shared-library-during-runtime/3855 but no replies.

Used https://bitmovin.com/demos/drm for testing.

So far, no luck.

Thanks for your time.

**Comment by Gaeldrin** [comment] 2023-06-24 10:10
Hello finesseseth, I am afraid I don't have good news for you.

This is a known issue (in a sense that at least I know about it), your research is actually quite similar to mine. Many of your points coincide with my attempts and results, some are new and thank you for them and thank you again for writing it all here. Let me answer a couple of your points:

- > Without this change I don't think Opera even attempts to load libwidevinecdm.so.

  I can confirm this, the browser needs working proprietary codecs to use Widevine. Opera states this in their official reddit manual (:smile:).

- > https://discourse.flathub.org/t/flatpak-dev-question-app-cannot-load-shared-library-during-runtime/3855 but no replies

  The question on Flathub Discourse is actually mine, that was when I was trying to figure it out and I hit the permission wall that I don't understand. And from the lack of answers I can only assume nobody else does either. :-/

One extra point I tried:
- Ran the Opera flatpak in debug mode (with `gdb` and/or `strace`, don't remember exactly) and got a lot of extra (but useless) output and exactly the same error messages.

### My opinion

1. I am not a specialist in any of these products (Flatpak, Opera, Widevine DRM,..) but for me, the result of debug run means that the Flatpak wrapper does not detect anything wrong. Therefore, to get more information we would need a developer version of Opera at minimum, Opera source codes at best. See how the code is structured in the `cdm_module.cc` up to line 115, maybe add some extra tests or checks and continue from there. I don't think it is real option and thus it is the first wall in the way of having Opera flatpak DRM working.
2. Second wall has appeared just some two weeks ago. I had the Chromium codecs package included but a version mismatch happened and now I don't feel good about having them included and just hoping it will work. But I am not interested in learning how to build them as a separate flatpak and connect them as a dependence to this flatpak. Changing the codecs manually is not the way. So sadly, no included codecs either.

Wtih these two problems, I am inclined to use other browsers to play video instead. Opera was my backup browser and that it does not handle video playback is a price I am willing to pay.

Uff, this turned out quite longer than expected, I salute everyone who made it here and wish you a nice day! :sun_with_face:

**Comment by finesseseth** [comment] 2023-06-24 13:38
Hi Gaeldrin, thanks for your reply.

That is very unfortunate, I'm even less familiar with Flatpak, Opera, and Widevine so I can't offer any new insights, except perhaps that `Operation not permitted` in general personal experience tends to be related to permissions or filesystem (IE mount options like noexec and writing to a ro mount). I tried looking in to the mounts in the sandbox but being unfamiliar with Flatpak I was unable to discern anything.

I read through the other issue raised about the codec's and my only suggestion there would be to look at other projects that do this, I know a lot of Flatpak's pull specific Mesa versions for example. This might apply to this current issue too, as I saw Vivaldi had similar issues as Opera. Though reading through their forums about Flatpak versions of Vivaldi wasn't spirit raising as they seemed to conclude that Flatpak needs to mature it's sandbox more, citing issues with it and Chromium based browsers needing to use something called Zypak, but you may already know this.

I'm really only knee deep in to using Flatpak's so I can still use Opera via other ways without breaking my work flow or system in the process.

Thanks for putting this whole thing together. If anything changes I'll be back.

**Comment by hfiguiere** [comment] 2023-09-15 19:24
I think it's a dupe of #28

**Closed** 2024-02-12 07:16 UTC
Labels: wontfix
